module.exports.usersController = require('./usersController')
module.exports.categoriesController = require('./categoriesController')
module.exports.itemsController = require('./itemsController')
module.exports.ratingsController = require('./ratingsController')
module.exports.cartsController = require('./cartsController')
module.exports.ordersController = require('./ordersController')
